# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [3]:
null_vec = np.zeros(10)
null_vec

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [4]:
vec1 = np.arange(10,50)
vec1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [5]:
np.shape(vec1)

(40,)

5. Print the type of the previous array in question 3

In [6]:
vec1.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [7]:
np.show_config()
np.__version__

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/saads/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/saads/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/saads/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 

'1.18.1'

7. Print the dimension of the array in question 3


In [8]:
vec1.ndim

1

8. Create a boolean array with all the True values

In [9]:
np.full(5, True)

array([ True,  True,  True,  True,  True])

9. Create a two dimensional array




In [10]:
np.arange(20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

10. Create a three dimensional array



In [11]:
np.arange(20).reshape(2,2,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [12]:
np.flipud(vec1)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

12. Create a null vector of size 10 but the fifth value which is 1 

In [13]:
vec2 = np.eye( 10 ) [ 5 - 1 ]
vec2

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [15]:
arr = np.array([1,2,3,4,5])
arr.astype(float)

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [16]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [17]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])

17. Extract all odd numbers from arr with values(0-9)

In [18]:
arr = np.arange(0,10)
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [19]:
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [20]:
arr = np.arange(10)
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [28]:
arr = np.ones((5,5))
arr[1:-1,1:-1] = 0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [27]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d[1,1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [31]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [43]:
arr = np.arange(9).reshape(3,3)
arr[:1]

array([[0, 1, 2]])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [40]:
arr = np.arange(9).reshape(3,3)
arr[1,1]

4

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [57]:
arr = np.arange(9).reshape(3,3)
arr[0:2,2]

array([2, 5])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [67]:
arr = np.random.random((10,10))
xmin, xmax = arr.min(), arr.max()
xmin, xmax

(0.013943864501041792, 0.9981516513519113)

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [72]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.intersect1d(a, b) 
c

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [75]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [77]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)

array([[-0.14715463, -0.33739354, -0.43005969, -0.55641603],
       [-1.29637208,  0.76521177,  0.97486173,  0.30404038],
       [-1.55180402, -0.71840789,  2.20007435,  1.07823295],
       [-0.70859541, -0.5599863 , -1.46169783, -0.34268547],
       [ 0.2835003 , -1.27521453,  1.05305852, -1.06877721],
       [ 0.35912073,  0.32116715,  0.90331265, -0.43550859],
       [ 1.11341356,  1.00091963,  0.73555932, -1.17006786]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [78]:
rand_arr = np.random.randint(low=1, high=15, size=(5,3)) + np.random.random((5,3))
rand_arr

array([[ 6.93753172,  9.82710969,  3.63570022],
       [ 6.2502807 ,  3.02490739,  8.93331421],
       [ 5.65627767,  9.10923474, 13.48982187],
       [13.02123012,  7.45090692,  6.38114452],
       [ 3.509735  , 10.43886058,  8.61350529]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [81]:
rand_arr = np.random.randint(low=1, high=16, size=(2,2,4)) + np.random.random((2,2,4))
rand_arr

array([[[ 9.07049039, 14.36850946,  6.12008678,  6.97036901],
        [ 4.10862672,  3.12544348, 13.92741506,  5.36254881]],

       [[ 8.32711558, 13.8611889 ,  1.77873756, 11.49409986],
        [11.3952565 , 13.87836698,  7.58583744,  5.48854953]]])

33. Swap axes of the array you created in Question 32

In [85]:
rand_arr.swapaxes(1,2)

array([[[ 9.07049039,  4.10862672],
        [14.36850946,  3.12544348],
        [ 6.12008678, 13.92741506],
        [ 6.97036901,  5.36254881]],

       [[ 8.32711558, 11.3952565 ],
        [13.8611889 , 13.87836698],
        [ 1.77873756,  7.58583744],
        [11.49409986,  5.48854953]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [94]:
arr = np.arange(10)
arr1 = np.sqrt(arr)
arr1[arr1 < .5] = 0
arr1

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [105]:
a = np.random.random((12))
b = np.random.random((12))
c = np.maximum(a, b)  
c

array([0.32661614, 0.26426727, 0.80625772, 0.72187508, 0.56725536,
       0.80842137, 0.22657617, 0.25213246, 0.4541805 , 0.53538403,
       0.71692834, 0.62867438])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [114]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names = np.unique(names)
names = np.sort(names)
names

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [116]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
np.setdiff1d(a, b)

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [125]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[0:3,1] = newColumn
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [127]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [143]:
arr = np.random.randn((20))
np.sum(arr)

-3.6646459792080464